### PR TITLE
`useSubscription` and `useLayoutSubscription`: allow `PartialObserver`

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes https://github.com/crimx/observable-hooks/issues/23

I need help with the following:

- Where to update docs?
- Should I update the changelog and if so is there a convention?
- How should I update the `@param` JS Doc?

### CODE REVIEW

**Comment by crimx** [comment]
> Where to update docs?

`/docs/api/README.md`

> Should I update the changelog and if so is there a convention?

No need to. Changelogs are generated automatically on releasing base on the conventional commit messages.

> How should I update the @param JS Doc?

`@param xxx What is xxx`

**Comment by crimx** [comment]
Thanks for the PR! LGTM. It seems like the coverage has dropped a bit.

**Comment by OliverJAsh** [comment]
Updated docs etc.

> It seems like the coverage has dropped a bit.

Do you have any suggestions you would like me to see to before we merge this? What tests do you think are worth adding?

**Comment by crimx** [comment]
LGTM. Thanks!

**Comment by OliverJAsh** [comment]
Would you be able to do a quick release to npm?

**Comment by crimx** [comment]
Will do asap. Fixing some ts4 issues.

**Comment by crimx** [comment]
released

**Pull request merged**
